export const courses = [
  // --- АЛГЕБРА 7 КЛАС ---
  {
    id: "alg-7-topic1-lesson",
    title: "Інтенсив: Урок",
    desc: "Теорія і практика",
    type: "lesson",
    subject: "algebra",
    grade: 7,
    filename: "math-intensive",
    badgeText: "Урок",
  },
  {
    id: "alg-7-topic1-hw",
    title: "Інтенсив: Домашка",
    desc: "Закріплення",
    type: "homework",
    subject: "algebra",
    grade: 7,
    filename: "math-intensive",
    badgeText: "ДЗ",
  },
  {
    id: "alg-7-topic1-test",
    title: "Інтенсив: Тест",
    desc: "Контроль знань",
    type: "test",
    subject: "algebra",
    grade: 7,
    filename: "math-intensive",
    badgeText: "Тест",
  },

  // --- АЛГЕБРА 8 КЛАС (Властивості кореня) ---
  {
    id: "alg-8-17-lesson",
    title: "Властивості кореня: Урок",
    desc: "Теорія та практика",
    type: "lesson", 
    subject: "algebra",
    grade: 8,
    filename: "17-arythmetic-root-properties", // Назва JSON файлу
    badgeText: "Урок",
  },
  {
    id: "alg-8-17-hw",
    title: "Властивості кореня: Домашка",
    desc: "Самостійне опрацювання",
    type: "homework",
    subject: "algebra",
    grade: 8,
    filename: "17-arythmetic-root-properties",
    badgeText: "ДЗ",
  },
  {
    id: "alg-8-17-test",
    title: "Властивості кореня: Тест",
    desc: "Перевірка знань",
    type: "test",
    subject: "algebra",
    grade: 8,
    filename: "17-arythmetic-root-properties",
    badgeText: "Тест",
  },
];
